### ISSUE TITLE
Compile Error - C Code - Hello World, Again (Solution)

### ISSUE THREAD

**Issue by pritchardtom** [rantahar/introduction-to-mpi#11]
Location: https://rantahar.github.io/introduction-to-mpi/03-mpi_send_recv/index.html (Hello Again, World > Solution)

Compiled with: GNU 8.1 + OpenMPI 3.1

Description:

When executing the code solution for the following problem: "**Modify the Hello World code so that each rank sends its message to rank 0. Have rank 0 print each message.**" the compiler throws the following error:

```
error: ‘r’ undeclared (first use in this function)
        for( int sender=1; sender<n_ranks; r++ ){
```

**Comment by edbennett** [comment]
Looks like that should be `sender++` rather than `r++`.

**Comment by pritchardtom** [comment]
I did try fixing this (replaced `r++` with `sender++`).  Program compiles, but executing `mpirun` produces the following:

```
[sl1:273263] *** An error occurred in MPI_Recv
[sl1:273263] *** reported by process [2088763393,0]
[sl1:273263] *** on communicator MPI_COMM_WORLD
[sl1:273263] *** MPI_ERR_TRUNCATE: message truncated
[sl1:273263] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[sl1:273263] ***    and potentially your MPI job)

```

**Comment by rantahar** [comment]
The second problem is the message buffer size. The message is longer than 20 characters.
