### ISSUE TITLE
Compile Error - C Code - Non-Blocking Communication > Solution

### ISSUE THREAD

**Issue by pritchardtom** [rantahar/introduction-to-mpi#12]
Location: https://rantahar.github.io/introduction-to-mpi/06-nonblocking/index.html (Non-Blocking Communication > Solution)

Compiled with: GNU 8.1 + OpenMPI 3.1

Description:  Following error produced when compiling with `mpicc`:

```
error: ‘request’ undeclared (first use in this function)
    MPI_Isend(send_message, n_numbers, MPI_INT, neighbour, 0, MPI_COMM_WORLD, &request);
```

**Comment by rantahar** [comment]
The request was undefined. In addition, the buffers were freed before calling MPI_Finalize, which can cause a segmentation fault.
