### ISSUE TITLE
Compile Error - C Code - Serial Poisson Code

### ISSUE THREAD

**Issue by pritchardtom** [rantahar/introduction-to-mpi#13]
Location: https://rantahar.github.io/introduction-to-mpi/09-parallellising_serial/index.html (Poisson Serial Code)

Compiled with: GNU 8.1 + OpenMPI 3.1

Description:

- There's an erroneous `}` in the following code block:

```
   // Create a start configuration with the field
   // u=10 at x=0
   for(j = 0;j <= GRIDSIZE+1; j++){}
      u[j][0] = 10.0;
   }
```

- However, on fixing this issue, compilation still crashes with following error:

```
/usr/bin/ld: /tmp/cc1gwr2y.o: undefined reference to symbol 'sqrt@@GLIBC_2.2.5'
/usr/lib64/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

**Comment by edbennett** [comment]
I think the latter issue is due to placement of the `-lm` in the link command. If you're not adding that flag, you need to add it; if you are, you need to change where in the command you place it.

**Comment by pritchardtom** [comment]
Firstly, I was being an idiot.  I had my `mpicc` hat on, and this code example does not have a `#include <mpi.h>` header.  So I fixed the for loop `{}` error and compiled with: `gcc -std=99 tmp.c` and get:

```
/tmp/ccHHpzak.o: In function `main':
tmp.c:(.text+0x410): undefined reference to `sqrt'
tmp.c:(.text+0x430): undefined reference to `sqrt'
collect2: error: ld returned 1 exit status
```

I'll have another look after lunch.

**Comment by edbennett** [comment]
Yep—`sqrt` is defined in the math library, which you need to explicitly link. Use `gcc -std=c99 tmp.c -lm` and it should work.

This should probably be explicitly mentioned in the tutorial.

**Comment by pritchardtom** [comment]
Yes, that's now working for me.  Thanks Ed.

**Comment by rantahar** [comment]
Removed the stray }
